### ISSUE TITLE
Support testing decorations

### ISSUE THREAD

**Issue by pokey** [pokey/cursorless-vscode#199]
We'd basically do all decorations through a mockable interface and then dump them along with the rest of the yaml. For actions that decorate twice, we could track both, and compare document contents at time of decoration to initial and final state, and then store them as pre- or post-decoration based on that

**Comment by AndreasArvidsson** [comment]
First draft
```yml
thatMark:
    - anchor: {line: 2, character: 4}
      active: {line: 2, character: 4}
    - anchor: {line: 4, character: 0}
      active: {line: 4, character: 0}
  decorations:
    - name: pendingDeleteBackground
      type: token
      start: {_line: 2, _character: 4}
      end: {_line: 2, _character: 10}
    - name: pendingDeleteBackground
      type: line
      start: {_line: 4, _character: 4}
      end: {_line: 4, _character: 18}
```
